
# 1. 模型配置
model:
  target: models.model_b2.SRCNN_B2
  params:
    in_channels: 9
    out_channels: 3
    # 理论上SRCNN不需要scale_factor，但为了统一，可以保留
    # scale_factor: 3

# 2. 数据配置
data:
  train:
    target: datapipe.datasets.PreprocessedTileDataset
    params:
      lr_dir: "./data/processed_data/train/LR"
      hr_dir: "./data/processed_data/train/HR"
      sample_num: 0  
      enable_hr_zero_filter: true
      hr_zero_ratio_filter_threshold: 0.05
      hr_zero_ratio_manifest: "./patch_stats.log"
      cache_dir: "/mnt/lm_data_afs/wangzining/charles/AEF_swinir/data/processed_data/cache/train"
      use_tile_cache: true        
      # scale_factor: 3
  val:
    target: datapipe.datasets.PreprocessedTileDataset
    params:
      lr_dir: "./data/processed_data/val/LR"
      hr_dir: "./data/processed_data/val/HR"
      sample_num: 8
      enable_hr_zero_filter: true
      hr_zero_ratio_filter_threshold: 0.05
      hr_zero_ratio_manifest: "./patch_stats.log"
      need_path: True
      cache_dir: "/mnt/lm_data_afs/wangzining/charles/AEF_swinir/data/processed_data/cache/val"
      use_tile_cache: true
      # scale_factor: 3
  test:
    target: datapipe.datasets.PreprocessedTileDataset
    params:
      lr_dir: "./data/processed_data/test/LR" 
      hr_dir: "./data/processed_data/test/HR"
      enable_hr_zero_filter: true
      hr_zero_ratio_filter_threshold: 0.05
      hr_zero_ratio_manifest: "./patch_stats.log"
      need_path: True
      sample_num: 8   
      # cache_dir: "/mnt/lm_data_afs/wangzining/charles/AEF_swinir/data/processed_data/cache/test"
      # use_tile_cache: true
      # scale_factor: 3
      # scale_factor: 3

# 3. 训练器配置
trainer:
  target: trainer_srcnn.TrainerSRCNN

# 4. 训练参数
train:
  save_dir: "./training_logs/srcnn_b2_3bands_run_1" # SRCNN的独立日志目录
  batch: [1, 1]
  iterations: 2000
  lr: 0.0001 
  lr_schedule: "ReduceLROnPlateau"
  lr_schedule_params:
    patience: 5
    factor: 0.5
  lr_min: 0.000001
  weight_decay: 0.0
  global_seeding: True
  seed: 42
  num_workers: 32
  val_num_workers: 8
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  amp: true
  amp_dtype: bf16
  cudnn_benchmark: true
  allow_tf32: true
  matmul_precision: "high"
  channels_last: true
  log_freq: [100, 200, 200]
  save_freq: 1000
  val_freq: 500
  rgb_chn: [0, 1, 2]
  local_logging: True

# 5. 推理配置
inference:
  padding_offset: 16
